### ISSUE TITLE
Consider using `Array`

### ISSUE THREAD

**Issue by int-index** [kowainik/typerep-map#20]
Right now we have

```
 , anys :: V.Vector Any
```

which under the hood is

```
data Vector a = Vector {-# UNPACK #-} !Int
                       {-# UNPACK #-} !Int
                       {-# UNPACK #-} !(Array a)
        deriving ( Typeable )
```

and I don't think we need the two `Int`s that come with it. We can cut the memory footprint by using `Array` directly.

Note that this is `Array` from the `primitive` package, not from the `array` package.

**Comment by int-index** [comment]
This also applies to unboxed vectors with `Word64`, which can be replaced with `PrimArray` (from the same `primitive` package).

**Comment by vrom911** [comment]
@int-index  I see that `Array` is just data wrapper for [`Array#`](https://hackage.haskell.org/package/ghc-prim-0.5.1.1/docs/GHC-Prim.html#t:Array-35-) from `ghc-prim`. Why not use it directly?

**Comment by int-index** [comment]
`primitive` has a more convenient interface and shouldn't have any performance cost (its operations should be inlined). I suggest starting with `Array` (the migration should be straightforward, and its unambiguous improvement), and then trying to replace `Array` with `Array#` and `PrimArray` with `ByteArray#` as a separate experiment.
