### ISSUE TITLE
Add 'hoist'

### ISSUE THREAD

**Issue by int-index** [kowainik/typerep-map#22]
```
hoist :: (forall x. f x -> g x) -> TypeRepMap f -> TypeRepMap g
```

This is basically a map over the elements. The associated keys are not changed in any way.

Having `hoist` means that we can declare `TypeRepMap` an instance of `MFunctor` from `mmorph`, although I'm not sure we should add this dependency.

**Comment by ChShersh** [comment]
@int-index What I usually do when I need to implement functions like `contramap`, `dimap` and `hoist` I just implement these functions on top-level so later if somebody wants instances he/she can just create instance on user side.

**Comment by int-index** [comment]
This would mean orphan instances, which aren't my favorite thing. But a newtype is always possible, so it's okay to omit the instance to avoid a large dependency.
