### ISSUE TITLE
Use cache-friendly binary search

### ISSUE THREAD

**Issue by ChShersh** [kowainik/typerep-map#3]
You can try to use different implementation of binary search algorithm (though still very simple). You can use cache-friendly binary search:

* http://bannalia.blogspot.ru/2015/06/cache-friendly-binary-search.html

This can improve performance of lookup. I guess you can create another module and implement it there. In order to implement this algorithm you need to perform two steps:

1. Implement `Vector` initialization from sorted list.
2. Implement cache-friendly binary search.

2 is simple, because algo itself is simple and there's C code in blog post. Though, 1 is a little bit more difficult...

1. First, you need to sort list.
2. Then you need to create possibly perfectly-balanced binary tree from this sorted list. Introduce your own 
```haskell
data Tree a = Leaf | Node a (Tree a) (Tree a)
```
3. Convert `Tree` to list using level-order.
4. Finally, just create `Vector` from this list.

So, probably initialization of `Vector` becomes slower. But AFAIU, this is not important. 

The only drawback: if first halves of `Fingerpint` are equal, you can't just increment index by 1 `i + 1` to search for the next key. But, assuming this is not important we can forget about this :) Or actually compare by second part of `Fingerptint` in case first part is equal. You can just print number of unique first halves of `Fingeprint`s in benchmark first (using just `print`) to see how many different elements there.

**Comment by int-index** [comment]
We already maintain that the vector is sorted.
