### ISSUE TITLE
Add an `Eq` instance on GHC 8.6+

### ISSUE THREAD

**Issue by int-index** [kowainik/typerep-map#47]
GHC 8.6 offers quantified constraints, meaning we can try to do something like this:

```
instance (forall a. Typeable a => Eq (f a)) => Eq (TypeRepMap f)
```

**Comment by ChShersh** [comment]
@int-index Could you recommend good tutorial on QuantifiedConstraints?

**Comment by int-index** [comment]
https://ryanglscott.github.io/2018/06/22/quantifiedconstraints-and-the-trouble-with-traversable/

Here's a three-part blog post series on `QuantifiedConstraints` from Ryan Scott.
