### ISSUE TITLE
Improve performance of `insert` and `delete` function

### ISSUE THREAD

**Issue by chshersh** [kowainik/typerep-map#57]
Currently performance of `insert` and `delete` is O(n log n) because those functions sort the list each time. But I guess it's possible to implement O(n). Though, it will be really painful.

Here are the steps:

1. Transform from tree-layout back to ordered-array layout: O(n).
2. Insert element to proper place by shifting array: O(n).
3. Transform back to tree layout: O(n).

But this issue should wait until we have benchmarks for `insert` and `delete` implemented:

* Blocked by: #56

**Comment by gdka** [comment]
Can you give me more details and the files that are you referring ? :)

**Comment by chshersh** [comment]
Hi @gdka! Thanks for your interest :slightly_smiling_face: I believe, this is already implemented by @ChrisPenner in #94, and the work is currently pending the review. Feel free to grab any other not-taken issue :slightly_smiling_face:

**Comment by chshersh** [comment]
@ChrisPenner Thanks for amazing performance improvements! :heart:
