### ISSUE TITLE
Hackage revision excludes Stackage's version of primitive

### ISSUE THREAD

**Issue by snoyberg** [kowainik/typerep-map#77]
Previous nightly snapshots included typerep-map and primitive 0.6.4. However, the recent [Hackage revision number 2](https://hackage.haskell.org/package/typerep-map-0.3.2/revisions/) excludes that version of primitive. Since we cannot upgrade to primitive 0.7 yet, I need to exclude this package from Stackage for now.

**Comment by chshersh** [comment]
@snoyberg Isn't it possible on Stackage to specify the precise revision of the package? While `primitive-0.7` is not on Stackage, it can contain `typerep-map` with the previous revision, and only after including `primitive-0.7` the newer revision can be used.

**Comment by snoyberg** [comment]
There's a section for ignoring all revisions, we don't have support right now for specifying exact revisions. But why is such a revision present if in fact the package works with the older version of primitive?

**Comment by chshersh** [comment]
@snoyberg Thanks for the information! I wasn't aware of such implementation details of the Stackage. Good to know 🙂 I revised `typerep-map` again, so now it should support both versions of `primitive`. Could you please return it back to Stackage?

> But why is such a revision present if in fact the package works with the older version of primitive?

In general, I prefer tighter bounds for dependencies. To have fewer surprises during work of the package.

**Comment by chshersh** [comment]
@snoyberg I've created PR on Stackage:

* https://github.com/commercialhaskell/stackage/pull/4685
