### ISSUE TITLE
Improve 'insert' performance even further

### ISSUE THREAD

**Issue by chshersh** [kowainik/typerep-map#99]
A few ideas after @ChrisPenner improvements:

* If the size is empty, use `one`
* If `member` is true, update the array cell and copy array

Any other ideas are appreciated :slightly_smiling_face:

**Comment by Yu-zh** [comment]
Do you think this is beginner friendly? I would be happy to contribute.

**Comment by ChrisPenner** [comment]
@Yu-zh  It may take a little learning to get used to some of the language extensions at play here; but should be pretty approachable!

The first optimization you'll probably want to use a "pattern guard" to check if the incoming map is empty, then use the `one` function to create a new map.

For the second optimization, you'll want to copy and _slightly_ adapt the code in `adjust` [here](https://github.com/ChrisPenner/typerep-map/blob/aeef5b8cf577a96cab44304c56724d7c86c169d2/src/Data/TypeRepMap/Internal.hs#L232-L238)

Feel free to take a look and let us know if you have questions 😄

**Comment by Yu-zh** [comment]
@ChrisPenner Thanks! I will take a look at the code.
